version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:

  Install:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
  
